export const CATEGORIE_CODE = [
    { id:9, code:  'CODE_CLIENT'},
    { id:10, code: 'CODE_FRNS'},
    { id:11, code: 'CODE_NDF'},
    { id:12, code: 'CODE_MULTIFRNS'},
    { id:13, code: 'CODE_MULTICLIENT'},
    { id:14, code: 'CODE_CAISSE'},
    { id:15, code: 'CODE_PROFORMA'},
    { id:16, code: 'CODE_BANQUE'},
    { id:17, code: 'CODE_INSTANCE1'},
    { id:18, code: 'CODE_IMAGE'},
    { id:19, code: 'CODE_ANPC'},
    { id:20, code: 'CODE_SOC'},
    { id:21, code: 'CODE_FISC'},
    { id:22, code: 'CODE_ILLISIBLE'},
    { id:23, code: 'CODE_COURRIER'},
    { id:24, code: 'CODE_JURIDIQUE'},
    { id:25, code: 'CODE_GESTION'},
    { id:27, code: 'CODE_ETATS_COMPTABLE'},
    { id:29, code: 'CODE_ANPC'},
    { id:37, code: 'CODE_EN_INSTANCE'},
    { id:41, code: 'CODE_A_RECATEGORISER'},
    { id:45, code: 'CODE_ECART'},
    { id:47, code: 'CODE_IMAGE'}
]
